tags:
  - MANTIS 筛选条件相关接口
summary:
  - 查询筛选条件
description:
    当 mode == private 时 creator 为必填项
parameters:
  - name: body
    in: body
    required: true
    schema:
      id: 查询筛选条件
      properties:
        mode:
          type: string
          example: "personal/public/all"
        page_num:
          type: integer
          example: 1
        page_size:
          type: integer
          example: 20
        creator:
          type: integer
          example: 1
        mapping_rule_id:
          type: integer
          example: 1
        filter_name:
          type: string
          example: 'xxx'


responses:
  200:
     description: 执行成功
     example:
  500:
     description: 执行失败
     example:
