services:
  mantis-test:
    build:
      context: ..
      dockerfile: ./docker_file/Dockerfile-mantis-test
    container_name: mantis-test
    environment:
      TZ: Asia/Shanghai
    ports:
      - "10053:10053"
    volumes:
      - ..:/home/project/testing/mantis
    command: nohup uwsgi --ini uwsgi.ini > op11.log 2>&1 &
    networks:
      - ta_network
    restart: unless-stopped


networks:
  default:
      external: true
      name: ta_network
