services:
  mantis-dev:
    build:
      context: ..
      dockerfile: ./docker_file/Dockerfile-mantis-dev
    container_name: mantis-dev
    environment:
      TZ: Asia/Shanghai
    ports:
      - "10052:10052"
    volumes:
      - ..:/home/project/develop/mantis
    command: nohup uwsgi --ini uwsgi.ini &
    networks:
      - mantis_dev_network
    restart: unless-stopped


networks:
  mantis_dev_network:
    driver: bridge

