services:
  mantis-pro:
    build:
      context: ..
      dockerfile: ./docker_file/Dockerfile-mantis-pro
    container_name: mantis-pro
    environment:
      TZ: Asia/Shanghai
    ports:
      - "10051:10051"
    volumes:
      - ..:/home/OnePlatform
    command: nohup uwsgi --ini uwsgi.ini > op11.log 2>&1 &
    networks:
      - op11_pro_network
    restart: unless-stopped


networks:
  op11_pro_network:
    driver: bridge

