CREATE DATABASE IF NOT EXISTS tms_db DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS tts_db DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS tm_db DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS ra_db DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS itc_db DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS mantis_db DEFAULT CHARSET utf8mb4;
CREATE DATABASE IF NOT EXISTS bmt_db DEFAULT CHARSET utf8mb4;